services:
  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:1.95.3
    container_name: n8n
    restart: always
    depends_on:
      - postgres
    ports:
      # - "5678:5678"
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=thirapat12
      - N8N_BASIC_AUTH_PASSWORD=LoveNaN#1312
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
    volumes:
      - ./n8n_data:/home/node/.n8n

# volumes:
#   postgres_data:
#   n8n_data:
